version: '3.7'

services:
    mail:
        image: mailhog/mailhog:latest
        networks:
            mail:
            f1monkey:
                aliases:
                    - f1monkey-mailhog
networks:
    f1monkey:
        external: true
    mail: